# Generated by Django 3.1.7 on 2021-02-25 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('state_code', models.CharField(max_length=10)),
                ('postal_code', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.CharField(default='0', max_length=10)),
                ('limit', models.IntegerField(default=200)),
                ('baths_min', models.IntegerField(default=None)),
                ('beds_min', models.IntegerField(default=None)),
                ('radius', models.IntegerField(default=None)),
                ('price_min', models.IntegerField(default=None)),
                ('sqft_min', models.IntegerField(default=None)),
                ('age_min', models.IntegerField(default=None)),
                ('lot_sqft_max', models.IntegerField(default=None)),
                ('price_max', models.IntegerField(default=None)),
                ('lot_sqft_min', models.IntegerField(default=None)),
                ('prop_type', models.CharField(choices=[('single_family', 'single_family'), ('multi_family', 'multi_family'), ('condo', 'condo'), ('mobile', 'mobile'), ('land', 'land'), ('farm', 'farm'), ('other', 'other')], default=None, max_length=20)),
                ('age_max', models.IntegerField(default=None)),
                ('sort', models.CharField(choices=[('sold_date', 'sold_date'), ('beds_high', 'beds_high'), ('price_low', 'price_low'), ('price_high', 'price_high'), ('lot_sqft_high', 'lot_sqft_high')], default=None, max_length=20)),
                ('sqft_max', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ComputeDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1 month', '1m'), ('3 months', '3m'), ('6 months', '6m'), ('One year', '12m')], default=None, max_length=20)),
                ('compare', models.CharField(choices=[('below', 'below'), ('above', 'above'), ('equals', 'equals')], default=None, max_length=20)),
                ('percentage_compare_average_price', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.adress')),
                ('assets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.assettypes')),
                ('computeDeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deal.computedeals')),
            ],
        ),
    ]
