# Generated by Django 3.1.7 on 2021-02-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
