# Generated by Django 3.1.7 on 2021-03-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0005_auto_20210309_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computedeals',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, '1 month'), (3, '3 months'), (6, '6 months'), (12, 'One year')], null=True),
        ),
    ]
